### ISSUE TITLE
关于词向量

### ISSUE THREAD

**Issue by biubiu202012** [zhangzhang66/CHIP2020_Entity#2]
您好，请问bert_vectors_768.txt这个文件中的词向量是直接用bert训练好的模型生成的，还是把项目的数据用bert进行预训练得到的？

**Comment by zjy03** [comment]
你好，这个问题你解决了吗，如果解决了，可以说一下方法吗，谢谢

**Comment by zhangzhang66** [comment]
不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zhangzhiyi0108** [comment]
> 您好，请问bert_vectors_768.txt这个文件中的词向量是直接用bert训练好的模型生成的，还是把项目的数据用bert进行预训练得到的？

直接用bert训练好的

**Comment by zhangzhiyi0108** [comment]
> 你好，这个问题你解决了吗，如果解决了，可以说一下方法吗，谢谢

不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zjy03** [comment]
好的，谢谢您，辛苦啦

**Comment by Just-silent** [comment]
> > 你好，这个问题你解决了吗，如果解决了，可以说一下方法吗，谢谢
> 
> 不好意思。回复晚了，我把词向量放在这里了，你可以直接。 下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

???
