### ISSUE TITLE
词向量

### ISSUE THREAD

**Issue by zjy03** [zhangzhang66/CHIP2020_Entity#3]
FileNotFoundError: [Errno 2] No such file or directory: '/home/zutnlp/data/bertvec/bert_vectors_768.txt'
您好，这个问题应该怎么解决

**Comment by zjy03** [comment]
这个bert_vectors_768这个文档怎样生成

**Comment by zhangzhiyi0108** [comment]
不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zjy03** [comment]
好的，谢谢您
